### ISSUE TITLE
Can't get this to work with Roon 1.8 (build 970)

### ISSUE THREAD

**Issue by Bananas-Are-Yellow** [docbobo/roon-extension-arcam#2]
I have a Squeezebox 3 connected to my Arcam AVR850 and I'd like to set up this extension to control the AVR850 volume directly from Roon.

I installed the **Roon Extension Manager**. Since the Arcam volume control extension is not listed, I assume it has not been converted to the newer Docker format. Any chance this can be done?

So I installed the **Extension Snapshot** extension, where it can be found. In the settings, I selected the Arcam volume control extension and the Start action. Then in the settings for the Arcam extension, I set the IP address of my AVR850.

After about 20 seconds, the Arcam volume control extension disappears from the list of extensions shown in Roon. I assume it crashed.

Is it out of date for the current Roon API?

I hope I can get this working. Any help would be appreciated.

**Comment by Bananas-Are-Yellow** [comment]
Here is the end of the log file for the **roon-extension-snapshots** Docker container:
```
2022-07-01T11:23:49.876Z - Inf: Started: roon-extension-arcam

-> CONTINUE 1 Changed {"message":"Started: roon-extension-arcam","is_error":false}

-> CONTINUE 1 Changed {"message":"Started: roon-extension-arcam","is_error":false}

<- REQUEST 34 com.roonlabs.settings:1/unsubscribe_settings {"subscription_key":"101"}

-> COMPLETE 34 Unsubscribed 

-> CONTINUE 1 Changed {"message":"Started: roon-extension-arcam","is_error":false}

-> CONTINUE 1 Changed {"message":"Started: roon-extension-arcam","is_error":false}

-> CONTINUE 1 Changed {"message":"Started: roon-extension-arcam","is_error":false}

-> CONTINUE 1 Changed {"message":"Started: roon-extension-arcam","is_error":false}

2022-07-01T11:25:29.208Z - Err: Process terminated: roon-extension-arcam (1)

-> CONTINUE 1 Changed {"message":"Process terminated: roon-extension-arcam (1)","is_error":true}

-> CONTINUE 1 Changed {"message":"Process terminated: roon-extension-arcam (1)","is_error":true}

-> CONTINUE 1 Changed {"message":"Process terminated: roon-extension-arcam (1)","is_error":true}

-> CONTINUE 1 Changed {"message":"Process terminated: roon-extension-arcam (1)","is_error":true}
```
Looks like **roon-extension-arcam** crashed.

**Comment by docbobo** [comment]
I honestly doubt that your problem is related to docker vs. non-docker. The extension is working correctly here on my end, both with or without extension manager. Nevertheless, I spent some time on the docker image and opened up a https://github.com/TheAppgineer/roon-extension-repository/pull/17

**Comment by Bananas-Are-Yellow** [comment]
Thank you. I'll try it as soon as it appears in the Extension Manager drop list.

**Comment by Bananas-Are-Yellow** [comment]
I'm away at the moment. I'll be able to test out the docker extension on Thursday.

**Comment by docbobo** [comment]
Glad you didn't try it right away, had to fix a minor bug. But it's working now - at least for me.

**Comment by Bananas-Are-Yellow** [comment]
Yes, it works, thank you.

By the way, does my Arcam AVR850 have a hostname or do I need to set a static IP address?

**Comment by docbobo** [comment]
Good question. I just ran an mDNS browser here and didn't see anything pop up related to my Arcam. I believe I looked into that a while ago and found out that Arcam is using some non-default mechanism for device discovery on the local network. But then again, my recollection might be wrong - has been a while.

I've set up a static IP address if that helps 😉
